


1. Load library:

```{r, message = FALSE}
library(tidyverse)
library(ggpubr)
```

2. Load data:

```{r, message = FALSE}
data <- read.table(file = "data/caste_weight_data.txt",
                   header = FALSE)

## Update column names:
colnames(data) <- c("weight",
                    "caste",
                    "species",
                    "colony")

data$species <- gsub(pattern = "ignitus",
                     replacement = "Bombus ignitus",
                     data$species)

data$colony <- gsub(pattern = 9,
                     replacement = 1,
                     data$colony)

data$species <- gsub(pattern = "lantschouensis",
                     replacement = "Bombus lantschouensis",
                     data$species)

data$species <- gsub(pattern = "montivagus",
                     replacement = "Bombus montivagus",
                     data$species)
```

3. Plot data:
For the purposes of examining the distrubution of weight across castes of three
bumblebee (Bombus) species, (a) histograms and (b) boxplots were generated for each:

a) Generation of histograms:

```{r, message = FALSE}
## Reorder levels for plotting:
data$caste <- factor(data$caste,
                     levels = c("worker",
                                "queen"))

data$combined <- paste(data$species,
                       " (",
                       data$colony,
                       ")",
                       sep = "")

## Reorder and relabel:
data$combined <- factor(data$combined,
                        levels = c("Bombus montivagus (1)",
                                   "Bombus ignitus (1)",
                                   "Bombus lantschouensis (1)",
                                   "Bombus ignitus (15)",
                                   "Bombus lantschouensis (15)"))

## For convenience, a function 'histogram_plotter' for generating
## histograms which takes a dataframe ('data') as input. The function
## outputs a ggplot-generated image:
histogram_plotter <- function(data){
  tmp <- ggplot(data = data,
       aes(x = weight,
           fill = species)) +
  xlab(label = "Weight [g]") +
  ylab(label = "Count") +
  geom_histogram(bins = 50) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold",
                                  size = 10),
        legend.title = element_text(face = "bold",
                                  size = 10),
        strip.text = element_text(face = "italic"),
                legend.position = "none")
  print(tmp)
}

## Perform for the first species:
plot1a <- histogram_plotter(data = subset(data,
                                combined == "Bombus montivagus (1)")) +
  facet_wrap(~combined) +
  scale_fill_manual(values = "gray")
 
## Perform for the second species:
plot2a <- histogram_plotter(data = subset(data,
                                combined == "Bombus ignitus (1)")) +
  facet_wrap(~combined) +
  scale_fill_manual(values = "orange")

plot3a <-  histogram_plotter(data = subset(data,
                                combined == "Bombus ignitus (15)")) +
  facet_wrap(~combined) +
  scale_fill_manual(values = "orange")

## Perform for the third species:
plot4a <- histogram_plotter(data = subset(data,
                                combined == "Bombus lantschouensis (1)")) +
  facet_wrap(~combined) +
  scale_fill_manual(values = "purple")

plot5a <- histogram_plotter(data = subset(data,
                                combined == "Bombus lantschouensis (15)")) +
  facet_wrap(~combined) +
  scale_fill_manual(values = "purple")

## For all histograms, combine into a multi-panel plot:
combined_1 <-  ggarrange(plot1a,
                         plot2a,
                         plot3a,
                         plot4a,
                         plot5a,
        nrow = 1,
        ncol = 5)
```

b) Generation of boxplots:

```
## For convenience, a function 'boxplotter' for generating
## boxplots which takes a dataframe ('data') as input. The function
## outputs a ggplot-generated image:
boxplotter <- function(data){
  tmp <- ggplot(data = data,
       aes(x = caste,
           y = weight,
           fill = combined)) +
  xlab("Caste") +
  ylab("Weight [g]") +
  geom_boxplot() +
  theme_bw() +
  theme(axis.title = element_text(face = "bold",
                                  size = 10),
        legend.title = element_text(face = "bold",
                                  size = 10),
        strip.text = element_text(face = "italic"),
        legend.position = "none")
  print(tmp)
}

## Perform for the first species:
plot1b <- boxplotter(data = subset(data,
                                combined == "Bombus montivagus (1)")) +
  facet_wrap(~combined) +
  scale_fill_manual(values = "gray")

## Perform for the second species:
plot2b <- boxplotter(data = subset(data,
                                combined == "Bombus ignitus (1)")) +
  facet_wrap(~combined) +
  scale_fill_manual(values = "orange")

plot3b <-  boxplotter(data = subset(data,
                                combined == "Bombus ignitus (15)")) +
  facet_wrap(~combined) +
  scale_fill_manual(values = "orange")

## Perform for the third species:
plot4b <- boxplotter(data = subset(data,
                                combined == "Bombus lantschouensis (1)")) +
  facet_wrap(~combined) +
  scale_fill_manual(values = "purple")

plot5b <- boxplotter(data = subset(data,
                                combined == "Bombus lantschouensis (15)")) +
  facet_wrap(~combined) +
  scale_fill_manual(values = "purple")

## Generate a second combined plot:
combined_2 <-  ggarrange(plot1b,
                         plot2b,
                         plot3b,
                         plot4b,
                         plot5b,
        nrow = 1,
        ncol = 5)
```

4. Combine and save:

```{r, message = FALSE
combined_plot <- ggarrange(combined_1,
          combined_2,
          nrow = 2,
          ncol = 1,
          align = "hv")

ggsave(filename = "results/combined_weight_distribution_caste_plot.png",
       plot = combined_plot,
       width = 12,
       height = 8)
```

5. Run lint:

```{r, message = FALSE}


```

