

```{r}
# Load libraries; install from scratch if needed
libraries <- c("readr", "DESeq2",
               "ggplot2",
               "ggpubr")
for (lib in libraries) {
    if (require(package = lib, character.only = TRUE)) {
        print("Successful")
    } else {
        print("Installing")
        source("https://bioconductor.org/biocLite.R")
        library(lib, character.only = TRUE )
    }
}
dir.create("results")
```

## Step One: Input results from star

We use raw, non-normalised estimated counts.
```{r} 
## Set paths to folders containing output files from kallisto
paths <- list()
paths$sample_batch_info <- "data/sample_information.txt"
paths$htseq_output   <- "input/ovary/"
# Set relative paths:
paths$htseq_files_relative <- grep(x = list.files(paths$htseq_output,
                                                     recursive = TRUE),
                                      pattern = ".tab",
                                      value   = TRUE)
paths$htseq_files <- file.path(paths$htseq_output,
                               paths$htseq_files_relative)
# Automatically extract file names from kallisto output for colnames
names(paths$htseq_files) <- gsub(paths$htseq_files_relative,
                                    pattern = "/.*",
                                    replacement = "")
for (filenumber in 1:length(paths$htseq_files)) {
  current_name <- names(paths$htseq_files)[filenumber]
  current_file <- paths$htseq_files[filenumber]
  if (FALSE == grepl(pattern = current_name, x = current_file)) {
    kill("we have a problem - names and filenames dont match up")
  }
}
```

## Step Two: Put sample names and treatments into a samples dataframe for DESeqDataSetFromTximport

```{r}
directory <- "./input/ovary/"

## Extract sample names and put into df for tximport
samples     <- data.frame(treatment = names(paths$htseq_files))
## Create a list of samples:
sample_files <- grep(".tab",
                    list.files(directory),
                    value = TRUE)

## Read in sample information for room and batch:
samples_information <- read.table(file = paths$sample_batch_info,
                                  header = FALSE,
                                  col.names = c("sample_name",
                                                "caste",
                                                "tissue",
                                                "stage",
                                                "treatment_group"),
                                  row.names = 1)

## Add row names and column names:
samples_information$sample_name <- row.names(samples_information)
samples_information$file_name <- row.names(samples_information)

samples_information <- samples_information[, c(5,6, 1:4)]

samples_information <- subset(x = samples_information,
                              tissue == "Ovary")

## Build DESeq2 dataset:
dds_htseq <- DESeqDataSetFromHTSeqCount(sampleTable = samples_information,
                                       directory = directory,
                                       design = ~ caste + stage + treatment_group)
keep <- rowSums(counts(dds_htseq)) >= 10
dds_htseq <- dds_htseq[keep, ]
#samples_to_keep <- colnames(counts(dds_htseq)) != "B37.ReadsPerGene.out.tab"
#dds_htseq <- dds_htseq[, samples_to_keep]

deseq_object  <- DESeq(dds_htseq,
                       test = "LRT",
                       reduced = ~caste + stage)

## Extract and save counts:
dds_htseq_counts <- counts(dds_htseq)
colnames(dds_htseq_counts) <- gsub(pattern = ".ReadsPerGene.out.tab",
                                   replacement = "",
                                   colnames(dds_htseq_counts))

## Save to file:
write.table(x = dds_htseq_counts,
            file = "results/all_ovary_counts.txt",
            row.names = TRUE,
            col.names = TRUE,
            quote = FALSE,
            sep = "\t")

## Normalise counts for principal component analysis:


## Check names of comparisons:
resultsNames(deseq_object)
## Extract results:
deseq_object_insemination <- results(deseq_object,
                                      name = "treatment_group_Insemination_group_vs_Control")

## Extract significant phenotype genes:
deseq_object_insemination$absL2FC <- abs(deseq_object_insemination$log2FoldChange)
deseq_object_insemination_sig     <- subset(x = deseq_object_insemination,
                                             padj < 0.05)
deseq_object_insemination_sig_up     <- subset(x = deseq_object_insemination,
                                             padj < 0.05 &
                                            log2FoldChange >= 1)
deseq_object_insemination_sig_down     <- subset(x = deseq_object_insemination,
                                             padj < 0.05 &
                                            log2FoldChange <= -1)
nrow(deseq_object_insemination_sig)
nrow(deseq_object_insemination_sig_up)
nrow(deseq_object_insemination_sig_down)

## Check names of comparisons:
resultsNames(deseq_object)

deseq_object_dilutent <- results(deseq_object,
                                      name = "treatment_group_Insemination_with_dilutent_vs_Control")

## Extract significant phenotype genes:
deseq_object_dilutent$absL2FC <- abs(deseq_object_dilutent$log2FoldChange)
deseq_object_dilutent_sig     <- subset(x = deseq_object_dilutent,
                                             padj < 0.05)
deseq_object_dilutent_sig_up     <- subset(x = deseq_object_dilutent,
                                             padj < 0.05 &
                                            log2FoldChange >= 1)
deseq_object_dilutent_sig_down     <- subset(x = deseq_object_results,
                                             padj < 0.05 &
                                            log2FoldChange <= -1)
nrow(deseq_object_dilutent_sig)
nrow(deseq_object_dilutent_sig_up)
nrow(deseq_object_dilutent_sig_down)

## Check names of comparisons:
resultsNames(deseq_object)

deseq_object_nothing <- results(deseq_object,
                                      name = "treatment_group_Insemination_with_nothing_vs_Control")

## Extract significant phenotype genes:
deseq_object_nothing$absL2FC <- abs(deseq_object_nothing$log2FoldChange)
deseq_object_nothing_sig     <- subset(x = deseq_object_nothing,
                                             padj < 0.05)
deseq_object_nothing_sig_up     <- subset(x = deseq_object_nothing,
                                             padj < 0.05 &
                                            log2FoldChange >= 1)
deseq_object_nothing_sig_down     <- subset(x = deseq_object_nothing,
                                             padj < 0.05 &
                                            log2FoldChange <= -1)
nrow(deseq_object_nothing_sig)
nrow(deseq_object_nothing_sig_up)
nrow(deseq_object_nothing_sig_down)

table(table(c(row.names(deseq_object_insemination_sig_up),
          row.names(deseq_object_dilutent_sig_up),
          row.names(deseq_object_nothing_sig_up))))

table(table(c(row.names(deseq_object_insemination_sig_down),
          row.names(deseq_object_dilutent_sig_down),
          row.names(deseq_object_nothing_sig_down))))
```

In terms of caste:

```{r, message = FALSE}
## Build DESeq2 dataset:
dds_htseq <- DESeqDataSetFromHTSeqCount(sampleTable = samples_information,
                                       directory = directory,
                                       design = ~ caste + stage + treatment_group)
keep <- rowSums(counts(dds_htseq)) >= 10
dds_htseq <- dds_htseq[keep, ]
#samples_to_keep <- colnames(counts(dds_htseq)) != "B37.ReadsPerGene.out.tab"
#dds_htseq <- dds_htseq[, samples_to_keep]

deseq_object  <- DESeq(dds_htseq,
                       test = "LRT",
                       reduced = ~treatment_group + stage)

## Check names of comparisons:
resultsNames(deseq_object)
## Extract results:
deseq_object_caste <- results(deseq_object,
                                      name = "caste_Worker_vs_Queen")

## Extract significant phenotype genes:
deseq_object_caste$absL2FC <- abs(deseq_object_caste$log2FoldChange)
deseq_object_caste_sig     <- subset(x = deseq_object_caste,
                                             padj < 0.05)
deseq_object_caste_sig_up     <- subset(x = deseq_object_caste,
                                             padj < 0.05 &
                                            log2FoldChange >= 1)
deseq_object_caste_sig_down     <- subset(x = deseq_object_caste,
                                             padj < 0.05 &
                                            log2FoldChange <= -1)
nrow(deseq_object_caste_sig)
nrow(deseq_object_caste_sig_up)
nrow(deseq_object_caste_sig_down)


## Build DESeq2 dataset:
dds_htseq <- DESeqDataSetFromHTSeqCount(sampleTable = samples_information,
                                       directory = directory,
                                       design = ~ caste + treatment_group + caste:treatment_group)
keep <- rowSums(counts(dds_htseq)) >= 10
dds_htseq <- dds_htseq[keep, ]
#samples_to_keep <- colnames(counts(dds_htseq)) != "B37.ReadsPerGene.out.tab"
#dds_htseq <- dds_htseq[, samples_to_keep]

deseq_object  <- DESeq(dds_htseq,
                       test = "LRT",
                       reduced = ~treatment_group + stage + caste)

## Check names of comparisons:
resultsNames(deseq_object)
## Extract results:
deseq_object_caste <- results(deseq_object,
                                      name = "caste_Worker_vs_Queen")

## Extract significant phenotype genes:
deseq_object_caste$absL2FC <- abs(deseq_object_caste$log2FoldChange)
deseq_object_caste_sig     <- subset(x = deseq_object_caste,
                                             padj < 0.05)
deseq_object_caste_sig_up     <- subset(x = deseq_object_caste,
                                             padj < 0.05 &
                                            log2FoldChange >= 1)
deseq_object_caste_sig_down     <- subset(x = deseq_object_caste,
                                             padj < 0.05 &
                                            log2FoldChange <= -1)
nrow(deseq_object_caste_sig)
nrow(deseq_object_caste_sig_up)
nrow(deseq_object_caste_sig_down)

## Check names of comparisons:
resultsNames(deseq_object)

deseq_object_dilutent <- results(deseq_object,
                                      name = "treatment_group_Insemination_with_dilutent_vs_Control")

## Extract significant phenotype genes:
deseq_object_dilutent$absL2FC <- abs(deseq_object_dilutent$log2FoldChange)
deseq_object_dilutent_sig     <- subset(x = deseq_object_dilutent,
                                             padj < 0.05)
deseq_object_dilutent_sig_up     <- subset(x = deseq_object_dilutent,
                                             padj < 0.05 &
                                            log2FoldChange >= 1)
deseq_object_dilutent_sig_down     <- subset(x = deseq_object_results,
                                             padj < 0.05 &
                                            log2FoldChange <= -1)
nrow(deseq_object_dilutent_sig)
nrow(deseq_object_dilutent_sig_up)
nrow(deseq_object_dilutent_sig_down)

## Check names of comparisons:
resultsNames(deseq_object)

deseq_object_nothing <- results(deseq_object,
                                      name = "treatment_group_Insemination_with_nothing_vs_Control")

## Extract significant phenotype genes:
deseq_object_nothing$absL2FC <- abs(deseq_object_nothing$log2FoldChange)
deseq_object_nothing_sig     <- subset(x = deseq_object_nothing,
                                             padj < 0.05)
deseq_object_nothing_sig_up     <- subset(x = deseq_object_nothing,
                                             padj < 0.05 &
                                            log2FoldChange >= 1)
deseq_object_nothing_sig_down     <- subset(x = deseq_object_nothing,
                                             padj < 0.05 &
                                            log2FoldChange <= -1)
nrow(deseq_object_nothing_sig)
nrow(deseq_object_nothing_sig_up)
nrow(deseq_object_nothing_sig_down)

table(table(c(row.names(deseq_object_insemination_sig_up),
          row.names(deseq_object_dilutent_sig_up),
          row.names(deseq_object_nothing_sig_up))))

table(table(c(row.names(deseq_object_insemination_sig_down),
          row.names(deseq_object_dilutent_sig_down),
          row.names(deseq_object_nothing_sig_down))))
```

Lastly, look at ovarian development:

```{r, message=TRUE}
dds_htseq <- DESeqDataSetFromHTSeqCount(sampleTable = samples_information,
                                       directory = directory,
                                       design = ~stage)

dds <- DESeq(dds_htseq,
             test = "LRT",
             reduced = ~1)
res <- results(dds)

## Check names of comparisons:
resultsNames(dds)

deseq_object_stage_i_ii <- results(dds,
                                      name = "stage_Stage_II_vs_Stage_I")

deseq_object_stage_i_ii_sig     <- subset(x = deseq_object_stage_i_ii,
                                             padj < 0.05)
deseq_object_stage_i_ii_sig_up     <- subset(x = deseq_object_stage_i_ii,
                                             padj < 0.05 &
                                            log2FoldChange >= 1)
deseq_object_stage_i_ii_sig_down     <- subset(x = deseq_object_stage_i_ii,
                                             padj < 0.05 &
                                            log2FoldChange <= -1)
nrow(deseq_object_stage_i_ii_sig)
nrow(deseq_object_stage_i_ii_sig_up)
nrow(deseq_object_stage_i_ii_sig_down)

deseq_object_stage_i_iv <- results(dds,
                                      name = "stage_Stage_IV_vs_Stage_I")

deseq_object_stage_i_iv_sig     <- subset(x = deseq_object_stage_i_iv,
                                             padj < 0.05)
deseq_object_stage_i_iv_sig_up     <- subset(x = deseq_object_stage_i_iv,
                                             padj < 0.05 &
                                            log2FoldChange >= 1)
deseq_object_stage_i_iv_sig_down     <- subset(x = deseq_object_stage_i_iv,
                                             padj < 0.05 &
                                            log2FoldChange <= -1)
nrow(deseq_object_stage_i_iv_sig)
nrow(deseq_object_stage_i_iv_sig_up)
nrow(deseq_object_stage_i_iv_sig_down)
```




```{r, message = FALSE}
vsd <- vst(deseq_object,
             blind = FALSE)

## Here set the two principal components that you want to compare:
## It can any combination between 1 and 22:
first_pc <- 1
second_pc <- 2
## Create function for plotting:
plotPCA.san <- function(object,
                        intgroup = "condition",
                        ntop = 1000,
                        returnData = FALSE) {
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop,
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  #return(pca)
  percentVar <- pca$sdev ^ 2 / sum(pca$sdev ^ 2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1,
                 paste,
                 collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  ## Select the PCAs and percentVar that you like instead of 1 and 2
  d <- data.frame(PC1 = pca$x[, first_pc],
                  PC2 = pca$x[, second_pc],
                  group = group, 
                  intgroup.df,
                  name = colData(vsd)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[first_pc:second_pc]
    return(d)
  }
    ggplot(data = d,
           aes_string(x = "PC1",
                      y = "PC2",
                      color = "group")) +
            geom_point(data = d,
                       aes(fill = group),
                       colour = "black",
                       pch = 21,
                       size = 3) +
            xlab(paste0("PC", first_pc, ": ",
                        round(percentVar[first_pc] * 100),
                        "% variance")) +
            ylab(paste0("PC", second_pc, ": ",
                        round(percentVar[second_pc] * 100),
                        "% variance")) +
            coord_fixed() +
            #geom_text_repel(size = 3) +
            theme_bw() +
            theme(axis.title = element_text(size = 15,
                                            face = "bold"),
                  axis.text = element_text(size = 10,
                                           face = "plain"),
                  legend.title = element_text(size = 15,
                                              face = "bold"),
                  legend.text = element_text(size = 15,
                                              face = "plain"),
                  legend.position = "top")
}

## Generate plot:
caste_plot <- plotPCA.san(vsd,
            intgroup = c("caste"))
caste_plot <- caste_plot + labs(fill = "Caste")

stage_plot <- plotPCA.san(vsd,
            intgroup = c("stage"))
stage_plot <- stage_plot + labs(fill = "Stage")

treatment_plot <- plotPCA.san(vsd,
                              intgroup = c("treatment_group"))
treatment_plot <- treatment_plot + labs(fill = "Treatment")

ggarrange(caste_plot,
          stage_plot,
          treatment_plot,
          nrow = 1,
          ncol = 3,
          labels = c("A",
                     "B",
                     "C"),
          align = "hv")

ggsave(filename = "results/combined_plot_all_ovary_samples.png",
       height = 5,
       width = 14)

## Identify and remove outliers:
## Calculate principal components:
pca <- prcomp(t(assay(vsd)))

pca_df <- as.data.frame(pca$x)

pca_df_subset <- subset(pca_df,
       PC2 > 20)

outlier_samples <- row.names(pca_df_subset)

## Remove outlier samples:
samples_to_keep <- !(colnames(counts(dds_htseq)) %in% outlier_samples)
dds_htseq <- dds_htseq[, samples_to_keep]

## Repeat:
keep <- rowSums(counts(dds_htseq)) >= 10
dds_htseq <- dds_htseq[keep, ]
#samples_to_keep <- colnames(counts(dds_htseq)) != "B37.ReadsPerGene.out.tab"
#dds_htseq <- dds_htseq[, samples_to_keep]
deseq_object  <- DESeq(dds_htseq,
                       test = "LRT",
                       reduced = ~caste + stage)

vsd <- vst(deseq_object,
             blind = FALSE)

## Generate plot:
caste_plot <- plotPCA.san(vsd,
            intgroup = c("caste"))
caste_plot <- caste_plot + labs(fill = "Caste")

stage_plot <- plotPCA.san(vsd,
            intgroup = c("stage"))
stage_plot <- stage_plot + labs(fill = "Stage")

treatment_plot <- plotPCA.san(vsd,
                              intgroup = c("treatment_group"))
treatment_plot <- treatment_plot + labs(fill = "Treatment")

ggarrange(caste_plot,
          stage_plot,
          treatment_plot,
          nrow = 1,
          ncol = 3,
          labels = c("A",
                     "B",
                     "C"),
          align = "hv")

ggsave(filename = "results/combined_plot_outliers_removed_ovary_samples.png",
       height = 5,
       width = 14)
```
